experimenter: JH
prep_choices: [Whole brain]
driver_choices: [nSyb-Gal4, LC10-1, LC10-2, LC10-3, TM9, TM3]
indicator_choices: [GCaMP6f, TdTomato, TNT, Chrimson]

rig_config:

  Bruker_TwoScreens_small:
    data_directory: E:/Jolie
    screen_center: [0, -30]
    rig: Bruker


