experimenter: MMP
prep_choices: [Left optic lobe (flat), Left optic lobe (tilted)]
driver_choices: [L1 (R66A01AD;R48A08DBD), L2 (21Dhh), Mi1 (R19F01), nsyb, 
                            Tm1 (R74G01), Tm3 (R13E12)]
indicator_choices: [ASAP2f, ASAP4c, ASAP4g, CD8-GFP, GCaMP6f, GCaMP6fu, GCaMP7fu, GFP, JEDI2P, jRGECO1b,
                            SF-iGluSnFR.A184V, SF-iGluSnFR.A184V.S72A, syt-GCaMP7fu]


rig_config:
  AODscope_OneScreen:
    data_directory: D:/Michelle/FlystimData
    screen_center: [180, 0]
    rig: AODscope

  Bruker_LeftScreen:
    data_directory: E:/Michelle
    screen_center: [0,-30]
    rig: Bruker
